version: "3.7"
services:
    rts-web:
        build:
            context: ./
            dockerfile: Dockerfile
        image: rts-web:1.0
        container_name: rts-web
        restart: unless-stopped
        working_dir: /var/www/rts-web
        ports:
            - "8080:80"
networks:
    default:
        external: true
        name: cicd
