version: "3.7"
services:
    rts_app1_web:
        build:
            context: ./
            dockerfile: Dockerfile
        image: php
        container_name: rts_app1_web
        restart: unless-stopped
        working_dir: /var/www/
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
        networks:
            - "rts-app"
networks:
    rts-app:
        driver: bridge
